[build]
  publish = "dist"
  command = "npm install --ignore-scripts && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_CONFIG_IGNORE_SCRIPTS = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

